---
- hosts: dev
  vars:
    - applications:
      - google-chrome
      - iterm2
      - brackets
      - sublime-text
      - java
      - intellij-idea-ce
      - dropbox
      - evernote
      - tunnelblick
      - virtualbox
      - vagrant
      - spectacle
      - teamviewer
      - rdm

  tasks:
    - name: Enable installing specific versions of casks
      shell: brew tap caskroom/versions

    - name: Check for installed apps(casks)
      shell: brew cask list | grep {{ item }}
      register: installed_applications
      with_items: '{{applications}}'
      ignore_errors: true

    - name: Install apps with brew-cask
      shell: brew cask install {{ item }}
      with_items: '{{applications}}'
      when: item not in installed_applications.results|map(attribute='stdout')

    - name: bash_profile
      copy: src=bash_profile dest=~/.bash_profile backup=yes  mode=770

    - name: install brew packages
      homebrew: update_homebrew=yes name={{ item }}
      with_items:
        - maven
        - wget
        - scala
        - sbt
        - python
        - tree
        - watch
        - ag
        - docker
        - mongo
        - typesafe-activator
        - pyenv-virtualenv
        - node
        - neo4j
        - nvm
        - chromedriver
        - redis

    - name: git config
      copy: src=gitconfig dest=~/.gitconfig backup=yes

    - name: git autocomplete
      copy: src=git-completion.bash dest=~/.git-completion.bash backup=yes mode=770

    - name: mongo dirs
      file: path={{item}} state=directory mode=777
      become: yes
      become_method: sudo
      with_items:
        - /data
        - /data/db
