---
- hosts: dev
  vars:
    - applications:
      - google-chrome
      - iterm2
      - brackets
      - sublime-text
      - java
      - intellij-idea
      - dropbox
      - evernote
      - tunnelblick
      - virtualbox
      - vagrant
      - spectacle
      - teamviewer

  tasks:
    - name: Enable installing specific versions of casks
      shell: brew tap caskroom/versions

    - name: Check for installed apps(casks)
      shell: brew cask list | grep {{ item }}
      register: installed_applications
      with_items: '{{applications}}'
      ignore_errors: true

    - name: Install apps with brew-cask
      shell: brew cask install {{ item }}
      with_items: '{{applications}}'
      when: item not in installed_applications.results|map(attribute='stdout')

    - name: install brew packages
      homebrew: update_homebrew=yes name={{ item }}
      with_items:
        - maven
        - wget
        - scala
        - sbt
        - python
        - tree
        - watch
        - ag
        - docker
        - typesafe-activator
        - pyenv-virtualenv
        - node
        - neo4j
        - nvm
        - chromedriver

    - name: git config
      copy: src=gitconfig dest=~/.gitconfig backup=yes
